Function Send-Email
{
    <#
        .SYNOPSIS
          Send-Email is intended to simplify the use of the Send-MailMessage cmdlet to send emails via powershell.

        .DESCRIPTION
          To simplify the use of Send-MailMessage however, it doesnt really accomplish that task as Send-MailMessage is already very simple to use. It will remain in this repo for my personal reference but may be removed in the future as it doesnt add to the quality of this module.

        .PARAMETER EmailFrom
          Specify the smtp address that the email will be from.

        .PARAMETER EmailTo
          Specify the smtp address which the email will be sent to.

        .EXAMPLE
          Send-Email -EmailFrom jdoe@bigcorp.com -EmailTo bross@consultant.com

          Sends an email message from jdoe@bigcorp.com to bross@consultant.com

        .NOTES
          NAME    : Send-Email
          AUTHOR  : BMO
          EMAIL   : brandonseahorse@gmail.com
          GITHUB  : github.com/Bmo1992
          CREATED : January 26, 2019
    #>

    [CmdletBinding()]
    Param
    (
        [Parameter(
            Mandatory=$True
        )]
        [string]$EmailFrom,
        [string]$EmailTo
    )

    #### VARIABLES ####
    $Subject = "AutoEmail"
    $Body = "This email was autogenerated using powershell"
    $SmtpServer = "smtp.office365.com"

    $user_credential = Get-Credential
    Send-MailMessage -To $EmailTo -From $EmailFrom -Subject $Subject -Body $Body -SmtpServer $SmtpServer -UseSsl -Credential `
    $user_credential -Port 587
}
